# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170928_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='hashing_rate',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='HashingRate',
        ),
    ]
